#============================================================================================================
#                                   PLUGIN SORT DE RITO | CONFIG
#============================================================================================================
#
#
#                                     _____ ____  ____  ______
#                                    / ___// __ \/ __ \/_  __/
#                                   \__ \/ / / / /_/ / / /
#                                  ___/ / /_/ / _, _/ / /
#                                /____/\____/_/ |_| /_/
#
#
#
#============================================================================================================
#                                   PLUGIN SORT DE RITO | CONFIG
#============================================================================================================

#-----------------------------------------------------------------------------------------------------------
#                                           COMMANDS
#-----------------------------------------------------------------------------------------------------------
cmd-name: "sort"
cmd-description: "Activer ou désactiver le menu des sorts !"


#-----------------------------------------------------------------------------------------------------------
#                                           MESSAGE
#-----------------------------------------------------------------------------------------------------------
message.active-menu: "Vous avez activer le menu des sorts, sneaker vous pour l'afficher !"
message.deactive-menu: "Vous avez deactiver le menu des sort !"
message.no-perm: "Vous n'avez pas la perm : perm.sort" # ACTIVER A TOUT LE MONDE PAR DEFAULT !